#!/bin/sh /etc/rc.common

START=91
STOP=91

USE_PROCD=1

hwnat_reg(){
	if [ -e "/etc/wireless/l1profile.dat" ]; then
		cat /etc/wireless/l1profile.dat | grep INDEX[0-9]_main_ifname | cut -d= -f2 >/tmp/iflist.log
		cat /tmp/iflist.log | while read line;do
		iwpriv $line set hw_nat_register=1
		done
		rm /tmp/iflist.log
	fi
}

start_service() {
	insmod /lib/modules/ralink/hw_nat.ko
	hwnat_reg
	mknod /dev/hwnat0 c 220 0
}

stop_service() {
	rmmod hw_nat.ko
	echo 'do nothing' > /dev/null
}


